version: '3.8'
services:
    nn-backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nn-back-app
        expose:
            - '${APP_PORT}'
        command: npm run start:prod
        volumes:
            - ./src:/usr/app/src
        ports:
            - '${APP_PORT}:${APP_PORT}'
        networks:
            - webnet
networks:
    webnet:



